[env:genericSTM32F411CE]
platform = ststm32
board = genericSTM32F411CE
framework = arduino
monitor_speed = 115200
upload_protocol = dfu
monitor_port = COM10
build_flags = 
    -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
lib_deps = askuric/Simple FOC@2.3.4